### ISSUE TITLE
Sparkfun hx711 compatibility

### ISSUE THREAD

**Issue by testower** [mpibpc-mroose/hx711#3]
* HX711 version: sparkfun (https://www.sparkfun.com/products/13879)
* Python version: 3.7
* Operating System: Raspbian Buster Lite Version:February 2020 Release date:2020-02-05 Kernel version:4.19

### Description

I tried to use your library but am seemingly unable to connect to the hardware for some reason. When trying to run the example I get the following (repeatingly):

```
WARNING:root:setting gain and channel took more than 60µs. Time elapsed: 0.00006646
```

### What I Did

Ran this code:
```
#!/usr/bin/python3
from hx711 import HX711
from RPi import GPIO
try:
    hx711 = HX711(
        dout_pin=5,
        pd_sck_pin=6,
        channel='A',
        gain=64
    )

    hx711.reset()   # Before we start, reset the HX711 (not obligate)
    measures = hx711.get_raw_data(num_measures=3)
finally:
    GPIO.cleanup()  # always do a GPIO cleanup in your scripts!

print("\n".join(measures))**
```

I have a sparkfun edition of the hx711. I connected the DAT pin to GPIO 5 and the CLK pin to GPIO 6. I have a raspberry pi model 3 b+. The VCC is connected to 5v pin.

Anything obvious I'm doing wrong?

**Comment by mpibpc-mroose** [comment]
Hi Tom,
the warning itself can bee seen quite frequently and should detect any malfunction. And no, I cannot see any obvious things which might get wrong. Do you get any output from the test script?

**Comment by testower** [comment]
I don't get any output apart from the warning. I suspect now though that I have possibly fried the GPIO, because I connected the VDD pin on the hx711 to 5v at one point during testing, without realising that it could send 5v to GPIO. It's a bit confusing because there seems to be different versions of the hx711 hardware around with different pin setups. Will test again on a new raspberry pi today.

EDIT: do you know if the VDD actually needs to be connected on this version?

**Comment by quixand** [comment]
I'm seeing a similar issue with an RPI1b. It looks like the clock cycle is quite reliable at around 16us measured on the scope but the python timing code adds a huge amount of time so the measured time is wildly inaccurate to the actual clock cycle time.
