### ISSUE TITLE
Getting Dual Channels To Work

### ISSUE THREAD

**Issue by gregpronko** [mpibpc-mroose/hx711#5]
* HX711 version: https://www.amazon.com/gp/product/B010FG9RXO/ref=ppx_yo_dt_b_asin_title_o04_s01?ie=UTF8&psc=1
* Python version: 3.7.6
* Operating System: balenalib/raspberrypi3-python:3.7.6

### Description

Hi there. I am trying to us your library to take measurements from two load cells.  I can either try to use two of the HX711 boards or just use one with Channel A & B.  I am trying to do the later and only use one board with two channels.  Can you let me know what I am doing wrong below.  I am running the below code in it own thread outputting global measurements to the other threads.  I keep getting this error:
WARNING:root:current channel != "A" so no need to set a gain current channel is 'B'
RIGHT RAW MEAN DATA: -45.19999999999982
LEFT RAW MEAN DATA: 357.59999999999854

### What I Did

Here is my code:

'#!/usr/bin/python3
from __future__ import print_function
import time
import threading
from hx711 import HX711
import RPi.GPIO as GPIO
import statistics

GPIO.setmode(GPIO.BCM)
left_calibration = 23380 # To try to calibrate each side to a TARE zero
right_calibration = 3390 # To try to calibrate each side to a TARE zero

def loadSensorBoth():
	global left_pressure
	global right_pressure
	while True:
		try:
			DataPin = 5
			ClockPin = 6
			NumReadings = 10
			print('READING HX711 LEFT')
			hxleft = HX711(dout_pin=5, pd_sck_pin=6, channel="A")
			print('LEFT RESET')
			resultleft = hxleft.reset()
			 if resultleft:
			 	print('LEFT READY TO USE')
			 else:
			 	print("LEFT NOT READY")
			left_pressure = ((statistics.mean(hxleft.get_raw_data(NumReadings))) - left_calibration)
			if left_pressure != False:
				print('LEFT RAW MEAN DATA: ' + str(left_pressure))
			else:
				print('LEFT INVALID DATA')
			GPIO.cleanup()
			print('READING HX711 RIGHT')
			hxright = HX711(dout_pin=5, pd_sck_pin=6, channel="B")
			print('RESET RIGHT')
			resultright = hxright.reset()
			if resultright:
			 	print('RIGHT READY TO USE')
			else:
			 	print("RIGHT NOT READY")
			right_pressure = ((statistics.mean(hxright.get_raw_data(NumReadings))) - right_calibration)
			if right_pressure != False:
				print('RIGHT RAW MEAN DATA: ' + str(right_pressure))
			else:
				print('RIGHT INVALID DATA')
			GPIO.cleanup()
		except (KeyboardInterrupt, SystemExit):
			print('BYE')
		finally:
			GPIO.cleanup()`

**Comment by mpibpc-mroose** [comment]
Sorry I have no experience with that. If you find out how this works it would be nice if your would contribute to the documentation about this topic.

**Comment by james-e-morris** [comment]
@gregpronko I had this need and developed my own solution. Can be found here: https://github.com/Morrious/hx711-multi. Hopefully I'm not too late for you :)
