### ISSUE TITLE
Library crashes Raspberry Pi

### ISSUE THREAD

**Issue by Grandpa-G** [mpibpc-mroose/hx711#6]
* HX711 version:
* Python version:
* Operating System:
Buster - Raspberry pi 4
### Description

I am using the example. As soon as the print message "Reset HX711" is printed, the Raspberry Pi shutdown. This happens if I don't have any device connected or not.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by mpibpc-mroose** [comment]
For me this sounds like a hardware or connection issue. Do you have the possibility to run the HX711 on another RasPi and/or another HX711?

**Comment by quixand** [comment]
Having a similar issue on a RPI 1B
`$ ./HX710B_low_pressure.py 
/home/pi/.local/lib/python3.7/site-packages/hx711/__init__.py:60: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self._pd_sck, GPIO.OUT)  # pin _pd_sck is output only
/home/pi/.local/lib/python3.7/site-packages/hx711/__init__.py:61: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
client_loop: send disconnect: Broken pipe
`
I then need to powercycle the pi

**Comment by quixand** [comment]
Ah, looks like GPIO 5 and 6 are not available on this model board. switched to gpio 17 and 21 which has allowed the init to complete. I have other errors now, of course. Perhaps update the example to use gpio that are available on all pi boards?

**Comment by mpibpc-mroose** [comment]
Thanks for bringing this up. Do you want to provide a pull request for that documentation change? Would be welcome!
