### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by lautaro2050** [mpibpc-mroose/hx711#9]
* HX711 version: 1.1.2.3
* Python version: 3.11.2
* Operating System: Raspbian 64bits aarch64

This library doesn't include the most important and principal functions to operate the hx711 (like a zero offset; a reference unit eg. calibration; among others)

This library "as is" it is only capable to take a raw reading that doesn't represent the real value of the weight you're trying to measure. The worst issue is that you will have to develop all the functions to do so. From the calibration reference to the actual weight measurement function. This library "as is" is not capable of doing anything useful with the hardware.

**Comment by mpibpc-mroose** [comment]
Thats completely correct. The library only provides very basic functionality to give the developers the degree of freedom they need. This is why a very basic example is included in the readme.

Please feel free to fork my project and extend it. Pull requests and contributions are welcome!
